//
//  SettingsView.swift
//  Clarity
//
//  Cross-platform settings panel. The OpenAI key is baked in via Secrets.swift,
//  so this is mostly status + maintenance affordances for now.
//

import SwiftUI

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(TaskStore.self) private var store

    @State private var showResetConfirmation = false

    var body: some View {
        #if os(iOS)
        NavigationStack {
            content
                .navigationTitle("Settings")
                .navigationBarTitleDisplayMode(.large)
        }
        #else
        VStack(spacing: 0) {
            macHeader
            content
        }
        .frame(minWidth: 480, idealWidth: 520, minHeight: 500, idealHeight: 600)
        #endif
    }

    private var content: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: AppSpacing.lg) {
                aiCard
                aboutCard
                dangerZoneCard
            }
            .padding(AppSpacing.lg)
        }
        .background(AppColors.background)
    }

    #if os(macOS)
    private var macHeader: some View {
        HStack {
            Text("Settings")
                .font(AppTypography.title)
                .foregroundStyle(AppColors.textPrimary)
            Spacer()
            Button("Done", action: { dismiss() })
                .buttonStyle(.plain)
                .foregroundStyle(AppColors.accent)
                .font(AppTypography.bodyMedium)
        }
        .padding(.horizontal, AppSpacing.lg)
        .padding(.top, AppSpacing.lg)
        .padding(.bottom, AppSpacing.sm)
    }
    #endif

    // MARK: - AI status

    private var aiCard: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            sectionLabel("AI")
            AppCard {
                HStack(spacing: 10) {
                    Circle()
                        .fill(AppColors.Priority.lowInk)
                        .frame(width: 8, height: 8)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("OpenAI configured")
                            .font(AppTypography.bodySemibold)
                            .foregroundStyle(AppColors.textPrimary)
                        Text("Day plans are generated by gpt-4o-mini.")
                            .font(AppTypography.caption)
                            .foregroundStyle(AppColors.textSecondary)
                    }
                    Spacer()
                }
            }
        }
    }

    // MARK: - About

    private var aboutCard: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            sectionLabel("About")
            AppCard {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Clarity")
                        .font(AppTypography.bodySemibold)
                        .foregroundStyle(AppColors.textPrimary)
                    Text("AI-powered day planning. Brain dump out loud, get a clean schedule back.")
                        .font(AppTypography.body)
                        .foregroundStyle(AppColors.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
    }

    // MARK: - Danger zone

    private var dangerZoneCard: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            sectionLabel("Danger zone")
            AppCard {
                VStack(alignment: .leading, spacing: AppSpacing.sm) {
                    Text("Reset all data")
                        .font(AppTypography.bodySemibold)
                        .foregroundStyle(AppColors.textPrimary)
                    Text("Permanently delete every task on this device. With iCloud Sync on, the deletion replicates to your other devices.")
                        .font(AppTypography.caption)
                        .foregroundStyle(AppColors.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                    Button {
                        showResetConfirmation = true
                    } label: {
                        Text("Reset all data")
                            .font(AppTypography.bodySemibold)
                            .foregroundStyle(AppColors.Priority.highInk)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 10)
                            .background(
                                Capsule(style: .continuous)
                                    .stroke(AppColors.Priority.highInk.opacity(0.5), lineWidth: 1)
                            )
                    }
                    .buttonStyle(PressableStyle(pressedScale: 0.98))
                }
            }
        }
        .alert("Reset all data?", isPresented: $showResetConfirmation) {
            Button("Cancel", role: .cancel) {}
            Button("Reset", role: .destructive) {
                store.deleteAll()
                #if os(macOS)
                dismiss()
                #endif
            }
        } message: {
            Text("This deletes every task. Can't be undone.")
        }
    }

    private func sectionLabel(_ text: String) -> some View {
        Text(text.uppercased())
            .font(AppTypography.captionSemibold)
            .tracking(0.6)
            .foregroundStyle(AppColors.textTertiary)
            .padding(.horizontal, 4)
    }
}
