//
//  SettingsView.swift
//  Clarity
//
//  Phase 8 — minimal settings tab. The OpenAI key is baked in via
//  Secrets.swift (gitignored), so no input UI is required.
//

#if os(iOS)
import SwiftUI

struct SettingsView: View {
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: AppSpacing.lg) {
                    aiCard
                    aboutCard
                }
                .padding(AppSpacing.lg)
            }
            .background(AppColors.background)
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.large)
        }
    }

    // MARK: - AI status

    private var aiCard: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            sectionLabel("AI")
            AppCard {
                HStack(spacing: 10) {
                    Circle()
                        .fill(AppColors.Priority.lowInk)
                        .frame(width: 8, height: 8)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("OpenAI configured")
                            .font(AppTypography.bodySemibold)
                            .foregroundStyle(AppColors.textPrimary)
                        Text("Day plans are generated by gpt-4o-mini.")
                            .font(AppTypography.caption)
                            .foregroundStyle(AppColors.textSecondary)
                    }
                    Spacer()
                }
            }
        }
    }

    // MARK: - About

    private var aboutCard: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            sectionLabel("About")
            AppCard {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Clarity")
                        .font(AppTypography.bodySemibold)
                        .foregroundStyle(AppColors.textPrimary)
                    Text("AI-powered day planning. Brain dump out loud, get a clean schedule back.")
                        .font(AppTypography.body)
                        .foregroundStyle(AppColors.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
    }

    private func sectionLabel(_ text: String) -> some View {
        Text(text.uppercased())
            .font(AppTypography.captionSemibold)
            .tracking(0.6)
            .foregroundStyle(AppColors.textTertiary)
            .padding(.horizontal, 4)
    }
}
#endif
